create extension if not exists pgcrypto;

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb
);

create table if not exists public.photo_entries (
  id uuid primary key default gen_random_uuid(),
  display_order integer not null,
  tag text not null,
  title text not null,
  copy text not null default '',
  note text not null default '',
  image text not null,
  comment_id text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.photo_comments (
  id bigint generated by default as identity primary key,
  photo_id text not null,
  author text not null default 'anoniem',
  body text not null,
  created_at timestamptz not null default now(),
  constraint photo_comments_author_length check (char_length(author) between 1 and 32),
  constraint photo_comments_body_length check (char_length(body) between 1 and 320)
);

create table if not exists public.page_visits (
  id bigint generated by default as identity primary key,
  session_id text not null,
  path text not null default '/',
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  username text primary key,
  password_hash text not null
);

create table if not exists public.admin_sessions (
  token text primary key,
  username text not null references public.admin_users(username) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create or replace function public.current_admin_token()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    nullif(current_setting('request.headers', true), '')::jsonb ->> 'x-admin-token',
    ''
  );
$$;

create or replace function public.current_admin_username()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    nullif(current_setting('request.headers', true), '')::jsonb ->> 'x-admin-username',
    ''
  );
$$;

create or replace function public.current_admin_password()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    nullif(current_setting('request.headers', true), '')::jsonb ->> 'x-admin-password',
    ''
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    exists (
      select 1
      from public.admin_sessions
      where token = public.current_admin_token()
        and expires_at > now()
    )
    or exists (
      select 1
      from public.admin_users
      where username = public.current_admin_username()
        and password_hash = crypt(public.current_admin_password(), password_hash)
    );
$$;

create or replace function public.admin_login(p_username text, p_password text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  stored_hash text;
  new_token text;
begin
  select password_hash
  into stored_hash
  from public.admin_users
  where username = p_username;

  if stored_hash is null or stored_hash <> crypt(p_password, stored_hash) then
    raise exception 'invalid login';
  end if;

  new_token := gen_random_uuid()::text;

  insert into public.admin_sessions (token, username, expires_at)
  values (new_token, p_username, now() + interval '30 days');

  return new_token;
end;
$$;

revoke all on function public.current_admin_token() from public;
grant execute on function public.current_admin_token() to anon, authenticated;

revoke all on function public.current_admin_username() from public;
grant execute on function public.current_admin_username() to anon, authenticated;

revoke all on function public.current_admin_password() from public;
grant execute on function public.current_admin_password() to anon, authenticated;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

revoke all on function public.admin_login(text, text) from public;
grant execute on function public.admin_login(text, text) to anon, authenticated;

alter table public.site_settings enable row level security;
alter table public.photo_entries enable row level security;
alter table public.photo_comments enable row level security;
alter table public.page_visits enable row level security;
alter table public.admin_users enable row level security;
alter table public.admin_sessions enable row level security;

drop policy if exists "settings leesbaar voor iedereen" on public.site_settings;
create policy "settings leesbaar voor iedereen"
on public.site_settings
for select
to anon, authenticated
using (true);

drop policy if exists "admin mag settings beheren" on public.site_settings;
create policy "admin mag settings beheren"
on public.site_settings
for all
to anon, authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "fotos leesbaar voor iedereen" on public.photo_entries;
create policy "fotos leesbaar voor iedereen"
on public.photo_entries
for select
to anon, authenticated
using (active = true or public.is_admin());

drop policy if exists "admin mag fotos beheren" on public.photo_entries;
create policy "admin mag fotos beheren"
on public.photo_entries
for all
to anon, authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "comments zijn leesbaar voor iedereen" on public.photo_comments;
create policy "comments zijn leesbaar voor iedereen"
on public.photo_comments
for select
to anon, authenticated
using (true);

drop policy if exists "iedereen mag comments plaatsen" on public.photo_comments;
create policy "iedereen mag comments plaatsen"
on public.photo_comments
for insert
to anon, authenticated
with check (
  char_length(author) between 1 and 32
  and char_length(body) between 1 and 320
);

drop policy if exists "admin mag comments verwijderen" on public.photo_comments;
create policy "admin mag comments verwijderen"
on public.photo_comments
for delete
to anon, authenticated
using (public.is_admin());

drop policy if exists "iedereen mag bezoeken opslaan" on public.page_visits;
create policy "iedereen mag bezoeken opslaan"
on public.page_visits
for insert
to anon, authenticated
with check (true);

drop policy if exists "admin mag bezoeken lezen" on public.page_visits;
create policy "admin mag bezoeken lezen"
on public.page_visits
for select
to anon, authenticated
using (public.is_admin());

drop policy if exists "niemand leest admin users direct" on public.admin_users;
create policy "niemand leest admin users direct"
on public.admin_users
for select
to anon, authenticated
using (false);

drop policy if exists "niemand leest admin sessions direct" on public.admin_sessions;
create policy "niemand leest admin sessions direct"
on public.admin_sessions
for select
to anon, authenticated
using (false);

insert into public.admin_users (username, password_hash)
values ('timvanoene', crypt('Pl@yst@tion', gen_salt('bf')))
on conflict (username) do update
set password_hash = excluded.password_hash;

insert into public.site_settings (key, value)
values (
  'hero',
  jsonb_build_object(
    'kicker', 'Vakantie-thijn',
    'title', 'Scroll en oordeel later.',
    'copy', 'Zwarte achtergrond, domme foto''s, en straks open comments onder elke foto zonder gedoe met accounts.',
    'button', 'begin'
  )
)
on conflict (key) do update
set value = excluded.value;

insert into public.photo_entries (display_order, tag, title, copy, note, image, comment_id, active)
values
  (1, '02:17', 'Er zijn foto''s waar je geen uitleg bij wilt geven en dit is er een van', 'Je opent de pagina, scrollt omlaag en dan krijg je dit gewoon vol in beeld. Precies de juiste energie.', 'Deze staat nu op plek 1.', 'assets/chatgpt-image-2026-07-02-191533.png', 'foto-1', true),
  (2, '13:10', 'Nieuwe afbeelding op plek 2, subtiel was blijkbaar geen optie', 'Je scrolt nog geen twee seconden en dan staat dit er al pontificaal tussen.', 'Afbeelding 2 is nu vervangen door je nieuwe versie.', 'assets/image-2-replacement.png', 'foto-2', true),
  (3, '16:28', 'Plek 3 is nu vervangen door pure vakantiechaos', 'Je hoeft hier eigenlijk niets meer aan uit te leggen, de foto doet het zware werk zelf al.', 'De oude derde afbeelding is vervangen door je nieuwe foto.', 'assets/image-3-replacement.png', 'foto-3', true),
  (4, '19:54', 'Plek 4 is nu vervangen door complete meme-ellende', 'Dit is precies zo''n foto die je niet uitlegt maar gewoon laat staan voor maximaal effect.', 'De oude vierde afbeelding is vervangen door je nieuwe versie.', 'assets/image-4-replacement.png', 'foto-4', true),
  (5, '23:43', 'Plek 5 is nu vervangen door nog meer cursed energie', 'Je denkt dat het niet gekker wordt en dan scroll je precies hiernaartoe.', 'Alleen plek 5 is aangepast zoals je vroeg.', 'assets/image-5-replacement.png', 'foto-5', true),
  (6, '08:11', 'Zijaanzicht met exact nul reden om dit prive te houden', 'Dit is gewoon zo''n foto die schreeuwt om onderaan een zwarte roast-scroll te eindigen.', 'Nieuwe echte foto toegevoegd als slotstuk.', 'assets/IMG_4568.JPG', 'foto-6', true),
  (7, '11:47', 'Nog een groepsfoto die totaal geen context nodig heeft', 'Dit is precies het type beeld dat steeds erger wordt naarmate je er langer naar kijkt.', 'Nieuw toegevoegd als extra kaart onderaan de feed.', 'assets/image-7-added.png', 'foto-7', true)
on conflict (comment_id) do update
set
  display_order = excluded.display_order,
  tag = excluded.tag,
  title = excluded.title,
  copy = excluded.copy,
  note = excluded.note,
  image = excluded.image,
  active = excluded.active;
