create table if not exists public.photo_comments (
  id bigint generated by default as identity primary key,
  photo_id text not null,
  author text not null default 'anoniem',
  body text not null,
  created_at timestamptz not null default now(),
  constraint photo_comments_author_length check (char_length(author) between 1 and 32),
  constraint photo_comments_body_length check (char_length(body) between 1 and 320)
);

alter table public.photo_comments enable row level security;

drop policy if exists "comments zijn leesbaar voor iedereen" on public.photo_comments;
create policy "comments zijn leesbaar voor iedereen"
on public.photo_comments
for select
to anon, authenticated
using (true);

drop policy if exists "iedereen mag comments plaatsen" on public.photo_comments;
create policy "iedereen mag comments plaatsen"
on public.photo_comments
for insert
to anon, authenticated
with check (
  char_length(author) between 1 and 32
  and char_length(body) between 1 and 320
);
